[db]
host = "localhost"
port = 5432
user = "admin"
password = "password"
database = "database"

[api]
host = "127.0.0.1"
port = 8000

[redis]
host = "localhost"
port = 6379
database = 0
username = ""
password = ""
